"""Corrección de nombre FavoriteTourPlan

Revision ID: 3696ebf5fc84
Revises: 738a181e05ac
Create Date: 2025-04-23 19:43:44.199982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3696ebf5fc84'
down_revision = '738a181e05ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'username')
    op.alter_column('reservation', 'reservation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('reservation', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CANCELLED', 'COMPLETED', name='reservationstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CANCELLED', 'COMPLETED', name='reservationstatus'),
               nullable=False)
    op.alter_column('reservation', 'reservation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('client', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
